### ISSUE TITLE
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor....错误

### ISSUE THREAD

**Issue by zwc456baby** [YinAoXiong/12306_code_server#3]
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(3, 3, 1, 64), dtype=float32) is not an element of this graph.

一次请求的完整报错:
```
[2019-12-19 16:41:21,102] ERROR in app: Exception on /verify/base64/ [POST]
Traceback (most recent call last):
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1119, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3468, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3547, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("Placeholder:0", shape=(3, 3, 1, 64), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/flask/app.py", line 1944, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/flask/app.py", line 1992, in try_trigger_before_first_request_functions
    func()
  File "/home/pi/udisk/projects/12306_code_server/app.py", line 23, in load_model
    textModel = models.load_model('model.v2.0.h5')
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/keras/engine/saving.py", line 287, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2470, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/media/pi/udisk/projects/12306_code_server/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1122, in _run
    e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(3, 3, 1, 64), dtype=float32) is not an element of this graph.
```

在同一台设备上，我使用 12306 python程序本地识别验证码可以正常使用，

但是当我 clone 这个项目，准备搭建验证码识别服务，运行后，请求时出现这个错误，服务无法正常使用

**Comment by zwc456baby** [comment]
![微信截图_20191219165043](https://user-images.githubusercontent.com/20961202/71158959-d0f30580-227f-11ea-8268-b71f5146470c.png)

看上去，似乎某种情况下， 启动了多个进程一样。
应该不是 `HadoopFileSystem load error` 错误导致的问题

因为即使出现 `HadoopFileSystem load error` ,tensorflow 也是可以正常使用的。

我的配置文件仅仅更改了 端口

**Comment by zwc456baby** [comment]
刚才更新到 1.1 版本，使用 tflite 替换 keras，出现下列错误

![微信截图_20191219165537](https://user-images.githubusercontent.com/20961202/71159512-bbcaa680-2280-11ea-877b-1bef054442d0.png)

**Comment by yinaoxiong** [comment]
@zwc456baby 你好，请问使用的平台和系统是什么？我在amd64，Ubuntu18.04上没有复现出这个问题。我更新了一下文档或许对你有帮助。还是建议使用容器部署

**Comment by zwc456baby** [comment]
使用的 arm 平台，debian 10 。后面我尝试 用容器吧

**Comment by zwc456baby** [comment]
使用 docker 运行成功
```
 http://s19.natfrp.org:19962/verify/base64/
```
